weather.api.key=33a2b8a7a4214b5897140231260707
weather.city=Buenos Aires

alerta.umbral.temperatura=45
alerta.umbral.humedad=60

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=a59dc7d25a1fc8
spring.mail.password=bad9213f07c309
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true